# Generated by Django 2.2.7 on 2019-11-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191117_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(default='', max_length=250),
        ),
    ]
