# Generated by Django 2.2.7 on 2019-11-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191117_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='sample heading', max_length=250)),
                ('body', models.TextField(default='sample heading', max_length=10000)),
                ('thumbail', models.ImageField(upload_to='blog/media')),
                ('author', models.CharField(default='admin', max_length=50)),
                ('published_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='draft', max_length=250)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(default='sample', max_length=50)),
                ('tags', models.CharField(default='sample, sample2', max_length=60)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
