# Generated by Django 2.2.7 on 2019-11-17 15:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20191117_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='post_id',
        ),
        migrations.AddField(
            model_name='entry',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='modified_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='entry',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
