# Generated by Django 2.2.7 on 2019-11-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20191117_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='post_id',
        ),
        migrations.AddField(
            model_name='entry',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
