# Generated by Django 2.2.7 on 2019-11-17 15:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20191117_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='id',
        ),
        migrations.AddField(
            model_name='entry',
            name='post_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 17, 15, 18, 26, 600993, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='entry',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 17, 15, 18, 26, 600948, tzinfo=utc)),
        ),
    ]
