# Generated by Django 2.2.7 on 2019-11-17 15:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20191117_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 17, 15, 38, 24, 441739, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='entry',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 17, 15, 38, 24, 441691, tzinfo=utc)),
        ),
    ]
