# Generated by Django 2.2.6 on 2019-11-18 06:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20191118_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='seo_description',
            field=models.CharField(default='sample SEO description', max_length=250),
        ),
        migrations.AddField(
            model_name='entry',
            name='seo_robot',
            field=models.CharField(default='sample SEO robot', max_length=80),
        ),
        migrations.AlterField(
            model_name='entry',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 18, 6, 25, 39, 874249, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='entry',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 18, 6, 25, 39, 874202, tzinfo=utc)),
        ),
    ]
