# Generated by Django 2.2.6 on 2019-11-18 06:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20191118_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 18, 6, 26, 7, 806691, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='entry',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 18, 6, 26, 7, 806644, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='entry',
            name='seo_description',
            field=models.TextField(default='sample SEO description', max_length=250),
        ),
    ]
